# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16eea5a21e4707328667dba57c59e2397a974b7b181451e4451f2a3d65acb23eeacad9f0fddf85b324c022911a1a41c78f13bf99deb92d3087435fd8a7d3ac20

test:
  secret_key_base: f5ec91de88cdf8d93af17f456b6df9fd3f22affca6f5a329726500129c2eaf9a66b66a58726ace28744e8ee72835e74a77ff85881df261564377e5968969ccc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
